// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaeyacnwxdikdkcvaxwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhZXlhY253eGRpa2RrY3ZheHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODMyNjIsImV4cCI6MjA2NTA1OTI2Mn0.7bRFXNoS2S8t8y1a4QnzNz43pAjkaSpZ78UnrGFb6bQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);